apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcollector
  namespace: production
  labels:
    app: stockcollector
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: stockcollector
  template:
    metadata:
      labels:
        app: stockcollector
    spec:
      containers:
        - name: stock-prod
          image: volkanakcora96/stock_collector
          command: ["/bin/bash", "-c"]
          args: ["./script.sh"]
          volumeMounts:
            - name: stock-prod-pv
              mountPath: /var
          ports:
            - containerPort: 9091
      dnsPolicy: "Default"
      dnsConfig:
        nameservers:
          - 8.8.8.8
      volumes:
        - name: stock-prod-pv
          persistentVolumeClaim:
            claimName: stockcollector-prod-claim
