apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - application-deployment.yaml
  - pvc.yaml 
  - service.yaml
  - stock-ingress.yaml

commonLabels:
  app.kubernetes.io/name: stockcollector


