apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: production
  labels:
    tier: production
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      tier: production
  template:
    metadata:
      labels:
        app: postgresql
        tier: production
    spec:
      containers:
        - name: postgresql
          image: postgres:latest # Replace with a specific version if needed
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: stock # Matches your Django config
            - name: POSTGRES_USER
              value: stock # Matches your Django config
            - name: POSTGRES_PASSWORD
              value: "2cNUVfN~Fp`2Zzh3EV2rcV49&~^Ev4y%%" # Matches your Django config (place in quotes)