apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15  # Replace with a specific version if needed
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: stock  # Matches your Django config
            - name: POSTGRES_USER
              value: stock  # Matches your Django config
            - name: POSTGRES_PASSWORD
              value: "2cNUVfN~Fp`2Zzh3EV2rcV49&~^Ev4y%%"  # Matches your Django config (place in quotes)
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: production
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockcollector-prod-claim
  namespace: production
  labels:
    tier: production
    app: stockcollector
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi