apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockcollector-prod-claim
  namespace: production
  labels:
    tier: production
    app: stockcollector
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi