- name: Deploy systemd unit
  become: true
  become_user: root
  template:
    src: "{{ backend_systemd_unit_src }}"
    dest: "{{ backend_systemd_unit_path }}"
    owner: root
    group: root
  register: deploy_unit

- name: Reload systemd daemon
  become: true
  become_user: root
  systemd:
    name: "{{ backend_systemd_unit }}"
    enabled: true
    daemon_reload: true
  when: deploy_unit.changed