- name: Trigger Build Role
  include_role:
    name: build_role

- name: Stop backend
  import_tasks: stop.yml
  tags: stop

- name: Install backend
  import_tasks: install.yml
  tags: install

- name: Configure SYstemD backend
  import_tasks: configure.yaml
  tags: configure

- name: Migrate Databas
  import_tasks: migrate_database.yaml
  tags: migrate_db

- name: Start backend
  import_tasks: start.yml
  tags: start
