- name: Migrate Database
  block:
    - name: Make Migrations Database
      command: 
        cmd: "{{ backend_venv_path }}/bin/stockcollector makemigrations"
        chdir: "{{ backend_path }}"
      register: makemigration_result
    
    - name: Migrate Database
      command: 
        cmd: "{{ backend_venv_path }}/bin/stockcollector migrate"
        chdir: "{{ backend_path }}"
      register: migration_result
