apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: stockcollector

# Example configuration for the webserver
# at https://github.com/monopole/hello
resources:
- deployment_app.yaml
- deployment_db.yaml
- postgres-pvc.yaml
- service.yaml
- pvc.yaml