apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stockcollector-prod-claim
  namespace: production
  labels:
    app: stockcollector
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi