apiVersion: v1
kind: Service
metadata:
  name: stockcollector-service
  namespace: production
spec:
  type: LoadBalancer  # Change to NodePort if not using a cloud provider
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: stockcollector
