# Generated by Django 4.2.11 on 2025-10-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockRealtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("stock_name", models.CharField(db_index=True, max_length=255)),
                ("price", models.FloatField()),
                ("volume", models.FloatField()),
                ("change_percent", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_stock_realtime",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "stock_name"],
                        name="data_stock__timesta_aaca0e_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="data_stock__timesta_38cc9f_idx"
                    ),
                    models.Index(
                        fields=["stock_name", "-timestamp"],
                        name="data_stock__stock_n_bc80f5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockBST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("open_price", models.FloatField(blank=True, null=True)),
                ("high_price", models.FloatField(blank=True, null=True)),
                ("low_price", models.FloatField(blank=True, null=True)),
                ("close_price", models.FloatField(blank=True, null=True)),
                ("adjusted_close", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("stock_name", models.CharField(max_length=255)),
                ("daily_return", models.FloatField(blank=True, null=True)),
                ("volatility", models.FloatField(blank=True, null=True)),
                ("daily_change", models.FloatField(blank=True, null=True)),
                ("high_low_spread", models.FloatField(blank=True, null=True)),
                ("expected_change", models.FloatField(blank=True, null=True)),
                ("magnitude", models.FloatField(blank=True, null=True)),
                ("context", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "data_stockbst",
                "indexes": [
                    models.Index(
                        fields=["date", "stock_name"],
                        name="data_stockb_date_a20994_idx",
                    ),
                    models.Index(fields=["-date"], name="data_stockb_date_0e6403_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("open_price", models.FloatField(blank=True, null=True)),
                ("high_price", models.FloatField(blank=True, null=True)),
                ("low_price", models.FloatField(blank=True, null=True)),
                ("close_price", models.FloatField(blank=True, null=True)),
                ("adjusted_close", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("stock_name", models.CharField(max_length=255)),
                ("daily_return", models.FloatField(blank=True, null=True)),
                ("volatility", models.FloatField(blank=True, null=True)),
                ("daily_change", models.FloatField(blank=True, null=True)),
                ("high_low_spread", models.FloatField(blank=True, null=True)),
                ("expected_change", models.FloatField(blank=True, null=True)),
                ("magnitude", models.FloatField(blank=True, null=True)),
                ("context", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "data_stock",
                "indexes": [
                    models.Index(
                        fields=["date", "stock_name"], name="data_stock_date_ee7ebb_idx"
                    ),
                    models.Index(fields=["-date"], name="data_stock_date_9e5441_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_code", models.CharField(db_index=True, max_length=10)),
                ("fund_name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("period", models.CharField(db_index=True, max_length=10)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_fund",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "fund_code"],
                        name="data_fund_created_0665ae_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="data_fund_created_99d2e3_idx"
                    ),
                    models.Index(
                        fields=["fund_code", "-created_at"],
                        name="data_fund_fund_co_be8b48_idx",
                    ),
                    models.Index(
                        fields=["fund_name", "-created_at"],
                        name="data_fund_fund_na_e262ef_idx",
                    ),
                ],
                "unique_together": {("created_at", "fund_code")},
            },
        ),
    ]
