# Generated by Django 4.2.11 on 2024-06-22 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={},
        ),
    ]
