# Generated by Django 4.2.11 on 2024-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="adjusted_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
