apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - pvc.yaml 
  - service.yaml

commonLabels:
  app.kubernetes.io/name: stockcollector


