apiVersion: v1
kind: Service
metadata:
  name: stock-prod-svc
  namespace: production
  labels:
    app: stockcollector
spec:
  type: NodePort
  selector:
    app: stockcollector
  ports:
    - port: 8080 # The port on which the service will be exposed
      targetPort: 9091 # The port to which traffic will be forwarded inside the pod
